version: "3.8"
services:
    web:
        image: "mark79/web"
        ports:
            - 80:80
        volumes:
            - "/home/vagrant/web:/var/www/html:ro"
        networks:
            - bgapp-net
        depends_on:
            - db
    db:
        image: "mark79/db"
        networks:
            - bgapp-net
        environment:
            MYSQL_ROOT_PASSWORD: "12345"
        restart: always
networks:
    bgapp-net:
       
